spring:
  data:
    elasticsearch:
      cluster-name: "elasticsearch"
      cluster-nodes: "127.0.0.1:9300"

spring.thymeleaf.cache: false
spring.thymeleaf.encoding: "UTF-8"
spring.thymeleaf.mode: "HTML5"
spring.thymeleaf.prefix: classpath:/templates/
spring.thymeleaf.suffix: ".html"
